### ISSUE TITLE
Exclude related individuals before analysis?

### ISSUE THREAD

**Issue by friedav** [nadineparker/ENIGMA_SCZ_MRS#1]
Dear Nadine,

should related individuals be excluded from the sample before running the analysis? We usually do so, but I saw some code chunks in the analysis script taking care of relatedness, so I was wondering if prior filtering is desired or not.

Thank you,
Friederike

**Comment by nadineparker** [comment]
Hi Friederike,
No need to remove related individuals. We estimate relatedness genetically and we will use this for our analyses. Thanks for asking.
